name: enigma_note
description: Generate passwords, take notes.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+7
environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  easy_localization: ^3.0.7
  hive: 2.2.3
  hive_flutter: 1.1.0
  uuid: 3.0.7
  flutter_native_splash: 2.2.19
  flutter_bloc: 8.1.2
  lottie: 2.3.2
  equatable: 2.0.5
  shared_preferences: 2.0.15
  google_mobile_ads: 3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.3.3
  hive_generator: 2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
    - assets/lotties/

  # example:
  fonts:
     - family: OpenSans
       fonts:
         - asset: assets/fonts/OpenSans-Regular.ttf
  
 
flutter_native_splash:
  color: "#000000"
  image: assets/images/icon.png
  android_12:
    image: assets/images/icon.png
    color: "#000000"